services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWD}"
    volumes:
      - './etc-pihole:/etc/pihole'
    networks:
      - homelab

networks:
  homelab:
    external: true
